fixups - works!

diff --git a/content/opt/setup/60-icingaweb2 b/content/opt/setup/60-icingaweb2
--- a/content/opt/setup/60-icingaweb2
+++ b/content/opt/setup/60-icingaweb2
@@ -1,6 +1,9 @@
 #!/bin/bash
 
 . /opt/helpers
+echo "Checking ini_set existence before execution"
+ls -l /usr/local/bin/ini_set || echo "ini_set not found"
+
 
 CNFSUFFIX=icingaweb2
 mysql_cnf_init_section \
